"""Typed telemetry data models and schemas for MantisGuard investigation engine."""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class MetricEvent(BaseModel):
    """Represents a single metric snapshot from an AI inference cluster."""

    timestamp: datetime
    cluster: str = Field(..., min_length=1, description="Target cluster identifier (e.g. cluster-a)")
    service: str = Field(..., min_length=1, description="Inference service name (e.g. vllm-inference)")
    gpu_utilization: float = Field(..., ge=0.0, le=100.0, description="GPU compute utilization percentage")
    gpu_memory_utilization: float = Field(..., ge=0.0, le=100.0, description="GPU VRAM utilization percentage")
    queue_depth: int = Field(..., ge=0, description="Number of requests waiting in queue")
    p95_latency_ms: float = Field(..., ge=0.0, description="95th percentile latency in milliseconds")
    error_rate: float = Field(..., ge=0.0, le=100.0, description="Error rate percentage")
    request_rate: float = Field(..., ge=0.0, description="Incoming request rate per second")


class LogEvent(BaseModel):
    """Represents a log entry emitted by an AI service or node."""

    timestamp: datetime
    cluster: str = Field(..., min_length=1)
    service: str = Field(..., min_length=1)
    severity: Literal["INFO", "WARN", "ERROR", "CRITICAL"] = Field(..., description="Log severity level")
    message: str = Field(..., min_length=1, description="Log message content")
    trace_id: Optional[str] = Field(default=None, description="Optional distributed trace correlation ID")


class TraceEvent(BaseModel):
    """Represents a distributed trace span from an inference request."""

    trace_id: str = Field(..., min_length=1, description="Unique trace identifier")
    timestamp: datetime
    cluster: str = Field(..., min_length=1)
    service: str = Field(..., min_length=1)
    duration_ms: float = Field(..., ge=0.0, description="Trace duration in milliseconds")
    status: Literal["OK", "ERROR", "TIMEOUT"] = Field(..., description="Trace completion status")
    parent_service: Optional[str] = Field(default=None, description="Upstream service identifier")


class EvidenceItem(BaseModel):
    """Represents an isolated evidence item extracted from telemetry anomaly detection."""

    source_type: Literal["metric", "log", "trace"] = Field(..., description="Origin source of evidence")
    timestamp: datetime
    cluster: str = Field(..., min_length=1)
    description: str = Field(..., min_length=1, description="Human-readable evidence summary")
    severity: Literal["INFO", "WARN", "ERROR", "CRITICAL"] = Field(..., description="Severity of observed anomaly")
    value: Optional[float] = Field(default=None, description="Optional numerical metric value")


class ClusterHealth(BaseModel):
    """Summary of cluster operational status and calculated health metrics."""

    cluster: str = Field(..., min_length=1)
    gpu_utilization: float = Field(..., ge=0.0, le=100.0)
    queue_depth: int = Field(..., ge=0)
    p95_latency_ms: float = Field(..., ge=0.0)
    error_rate: float = Field(..., ge=0.0, le=100.0)
    root_cause_score: float = Field(default=0.0, ge=0.0)
    health_status: Literal["HEALTHY", "DEGRADED", "CRITICAL"] = Field(default="HEALTHY")


class Recommendation(BaseModel):
    """Actionable recommendation generated by the investigation engine."""

    action: str = Field(..., min_length=1, description="Recommended remediation action (e.g., shift traffic)")
    source_cluster: str = Field(..., min_length=1, description="Cluster experiencing issues")
    target_cluster: Optional[str] = Field(default=None, description="Target healthy cluster for traffic shift")
    traffic_percentage: Optional[float] = Field(default=None, ge=0.0, le=100.0, description="Percentage of traffic to shift")
    reason: str = Field(..., min_length=1, description="Justification for recommendation")
    safety_notes: str = Field(default="Simulated recommendation only. Verify cluster capacity before execution.", min_length=1)


class InvestigationResult(BaseModel):
    """Complete root-cause investigation result contract for downstream dashboard consumers."""

    incident_title: str = Field(..., min_length=1)
    severity: Literal["INFO", "WARN", "ERROR", "CRITICAL"] = Field(...)
    affected_cluster: str = Field(..., min_length=1)
    root_cause: str = Field(..., min_length=1)
    confidence: float = Field(..., ge=0.0, le=100.0, description="Calculated confidence percentage (0-100)")
    evidence: List[EvidenceItem] = Field(default_factory=list)
    correlated_timeline: List[Dict[str, Any]] = Field(default_factory=list)
    cluster_health: List[ClusterHealth] = Field(default_factory=list)
    recommendation: Recommendation
    explanation: str = Field(..., min_length=1)
